stages:
  - release

semantic_release:
  image: node:12
  stage: release
  only:
    - master
  script:
    - npm i
    - npm install @semantic-release/gitlab @semantic-release/exec
    - npx semantic-release
