stages:
  - fetch-version
  - build
  - release
fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec
    - npx semantic-release --generate-notes false --dry-run
  artifacts:
    paths:
    - VERSION.txt
generate-non-semantic-version:
  stage: fetch-version
  except:
    refs:
    - master
  script:
    - echo build-$CI_PIPELINE_ID > VERSION.txt
  artifacts:
    paths:
    - VERSION.txt
build:
  stage: build
  script:
    - echo "Version is $(cat VERSION.txt)"
release:
  image: node:13
  stage: release
  only:
    refs:
    - master
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec
    - npx semantic-release
