image: alpine:latest

#      - validate / lint 
#      - plan_examples
#      - approve
#      - auto-release

variables:
  PLAN: plan.tfplan
  PLAN_JSON: tfplan.json
  TF_ROOT: ${CI_PROJECT_DIR}
  TERRAFORM_VERSION: "0.14.3"
  TF_IN_AUTOMATION: "TRUE"
  TFLINT_VERSION: "v0.23.0"
  TF_DOCS_VERSION: "0.6.0"
cache:
  paths:
    - tfplan.enc.zip

stages:
  - pre-checks
  - tf-lint
  - plan
  
  
precommit:
  stage: pre-checks
  image: python:buster
  before_script:
    - apt-get update
    - apt-get install -y shellcheck zip jq
    - TF_ZIP="terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
    - wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TF_ZIP}"
    - unzip ${TF_ZIP} && rm ${TF_ZIP}
    - mv terraform /usr/bin/terraform
    - curl -Lo ./terraform-docs https://github.com/terraform-docs/terraform-docs/releases/download/v0.10.1/terraform-docs-v0.10.1-linux-amd64
    - chmod +x  ./terraform-docs
    - mv ./terraform-docs /usr/bin/terraform-docs 
    - pip3 install pre-commit
  script:
    - pre-commit run --all-files


terraform-lint:
  stage: tf-lint
  before_script:
     - apk add zip git
     - TF_LINT_ZIP="tflint_linux_amd64.zip"
     - wget https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION=}/${TF_LINT_ZIP}
     - unzip ${TF_LINT_ZIP} && rm ${TF_LINT_ZIP}
     - mv tflint /usr/bin
  script:
   - tflint 

terraform-plan:
  stage: plan
  before_script:
    - apk add zip jq git
    - TF_ZIP="terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
    - wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TF_ZIP}"
    - unzip ${TF_ZIP} && rm ${TF_ZIP}
    - mv terraform /usr/bin/terraform
    - echo ${GCP_CREDENTIALS} > key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=key.json
  script:
    - terraform init -input=false
    - terraform plan -input=false
    - terraform show -json | jq -r '([.resource_changes[]?.change.actions?]|flatten)|{"create":(map(select(.=="create"))|length),"update":(map(select(.=="update"))|length),"delete":(map(select(.=="delete"))|length)}' > plan.json
  artifacts:
    name: TerraformPlan
    reports:
      terraform: plan.json
